#!/bin/bash
#
# AllStarLink extnodes generator
#
# Copyright (C) 2018-2024, AllStarLink, Inc.
#
# Written by:
# Tim Sawyer, WD6AWP
# Rob Vella, KK9ROB (send patch diff instead of full file)
# Steve N4IRS
# Jason McCormick, N8EI (modernization for systemd, packaging)
#
# See http://allstarlink.org for more information about
# this project. Please do not directly contact
# any of the maintainers of this project for assistance;
# the project provides a web site, and mailing lists
# for your use.
#
# This program is free software, distributed under the terms of
# the GNU General Public License Version 3. See the LICENSE file
# at the top of the source tree.

NODE_DB_HOST=snodes.allstarlink.org
URI="diffnodes.php"
NODE_URL="http://${NODE_DB_HOST}/${URI}"
USERAGENT="asl3-update-nodelist/1.0"

FILEPATH=/var/lib/asterisk
NODELIST=rpt_extnodes
EXTNODES=$FILEPATH/$NODELIST
HASH_FILE=$FILEPATH/asl3un-hash

# both-mode throttle: rpt_extnodes is DNS failover only (see issue #11)
# BOTH_UPDATE_INTERVAL and DNS_PROBE_NODE may be overridden via
# systemctl edit asl3-update-nodelist.service (see asl3-update-nodelist(1)).
BOTH_UPDATE_INTERVAL=${BOTH_UPDATE_INTERVAL:-86400}
DNS_PROBE_NODE=${DNS_PROBE_NODE:-2000}
DEFAULT_DNS_NODE_DOMAIN=nodes.allstarlink.org

getLastHash() {
	last_hash=$(head -n1 ${HASH_FILE})
}

writeHash() {
	curr_hash=$(grep SHA1 $EXTNODES | cut -d "=" -f 2 | tail -n 1)
	echo "${curr_hash}" > $HASH_FILE
}

downloadNodelist() {
	#echo "downloading \"${NODE_URL}${1}\""
	wget --user-agent="$USERAGENT" -q -O $EXTNODESTMP "${NODE_URL}${1}"
	if [ $? -ne 0 ]; then
		echo "failed to download from ${NODE_URL}"
		rm -f $EXTNODESTMP
		exit 1
	fi
}

writeNodelist() {
	# Q? does app_rpt need the file not to change?
	cat ${1} > ${EXTNODES}
	writeHash
	#echo "${NODELIST} updated"
}

dnsProbe() {
	local domain probe

	if [ -r /etc/asterisk/rpt.conf ]; then
		domain=$(grep -iE '^dns_node_domain' /etc/asterisk/rpt.conf | \
			perl -pe 's/^dns_node_domain\s?=\s?(\S+).*$/$1/gi' | \
			tr '[:upper:]' '[:lower:]' | tail -n1)
	fi
	domain=${domain:-${DEFAULT_DNS_NODE_DOMAIN}}
	probe="_iax._udp.${DNS_PROBE_NODE}.${domain}"
	host -t SRV "${probe}" >/dev/null 2>&1
}

# Return 0 when a both-mode update should be skipped.
shouldThrottleBothMode() {
	local now file_mtime file_age

	if [ ! -s "${EXTNODES}" ]; then
		return 1
	fi

	now=$(date +%s)
	file_mtime=$(stat -c %Y "${EXTNODES}" 2>/dev/null || echo 0)
	file_age=$(( now - file_mtime ))
	if [ "${file_age}" -ge "${BOTH_UPDATE_INTERVAL}" ]; then
		return 1
	fi

	if ! dnsProbe; then
		return 1
	fi

	return 0
}

# Check to see if this host is even using me
# Values are read from /etc/asterisk/rpt.conf directly (not #include files).
LUT=$( grep -iE '^node_lookup_method' /etc/asterisk/rpt.conf | \
	perl -pe 's/^node_lookup_method\s?=\s?(\S+).*$/$1/gi' | tr '[A-Z]' '[:lower:]' | tail -n1)
if [ "x${LUT}" = "xdns" ]; then
	echo "node_lookup_method = dns; skipping"
	exit 0
fi

if [ "x${LUT}" = "xboth" ] && shouldThrottleBothMode; then
	echo "node_lookup_method = both; skipping"
	exit 0
fi

# See if this is a full or differential
[ ! -f $HASH_FILE ] && touch $HASH_FILE
QS=""
getLastHash
[ "${last_hash}" != '' ] && QS="?hash=${last_hash}"

# Download the Nodelist
EXTNODESTMP=$(mktemp)
downloadNodelist "${QS}"

diff_type=$(head -n1 ${EXTNODESTMP} | sed -e 's/^;//g')
case $diff_type in
	Full)
		# Does app_rpt need the file not to change?
		writeNodelist ${EXTNODESTMP}
		;;

	Empty)
		touch ${EXTNODES}
		#echo "${NODELIST} unchanged"
		;;

	Diff)
		#echo "applying patch"
		NEW_FILE=$(mktemp)
		cp ${EXTNODES} ${NEW_FILE}
		patch --no-backup-if-mismatch -t -s -r 1 ${NEW_FILE} ${EXTNODESTMP}
		if [ $? -eq 0 ]; then
			# if all hunks applied successfully
			writeNodelist ${NEW_FILE}
		else
			# if some hunks cannot be applied or there were merge conflicts
			# or there is more serious trouble, download the "Full" Nodelist
			downloadNodelist ""
			writeNodelist ${EXTNODESTMP}
		fi
		rm $NEW_FILE
		;;
esac

rm $EXTNODESTMP

if [ ${USER} != "asterisk" ]; then
	chown asterisk:asterisk ${EXTNODES} ${HASH_FILE}
	chmod 644 ${EXTNODES} ${HASH_FILE}
fi

exit 0
